### ISSUE TITLE
WebradioDB compatibility as another open alternative server like Radio-Browser.info

### ISSUE THREAD

**Issue by goliv04053** [matteo-pacini/RadioGoGo#12]
There is a guy who made an alternative to Radio-Browser because the main repo didn’t make space to edit radio stations.

Here his project and repo
https://github.com/jcorporation/webradiodb
https://jcorporation.github.io/webradiodb/

**Comment by Zi0P4tch0** [comment]
Hello @goliv04053,

Thanks for introducing me to WebradioDB. It's always good to be aware of alternative projects like Radio-Browser. As of now, RadioGoGo is closely integrated with the RadioBrowser API, and switching or adding another backend would be a significant undertaking, especially as I'm still in the process of enhancing the core features.

However, I'm always attentive to the feedback and interests from the community. I'll leave this issue open and mark it with a `wontfix` label for the time being. If there's significant community interest and demand, I'll certainly re-evaluate the possibility in the future.

Thank you for your understanding and for your valuable input to  project!
